name: SonarCloud Scan 

on:
  push:
    branches:
      - main  

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
        SONAR_PROJECT_KEY: ${{secrets.SONAR_PROJECT_KEY}}
