name: SonarCloud 

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Install WPScan dependencies
      run: |
        sudo apt update
        sudo apt install ruby-full build-essential zlib1g-dev liblzma-dev libcurl4-openssl-dev -y
        sudo gem install wpscan

    - name: Run WPScan and output to JSON
      env:
        WPSCAN_API_TOKEN: ${{ secrets.WPSCAN_API_TOKEN }}
      run: |
        wpscan --url https://3.7.46.140.com \
               --api-token $WPSCAN_API_TOKEN \
               --format json \
               -o wpscan-results.json

    - name: Upload WPScan results
      uses: actions/upload-artifact@v4
      with:
        name: wpscan-results
        path: wpscan-results.json
